import * as React from "react";
import { Grid, Box } from "@mui/material";
// import  Box  from '@mui/material/Box';
import { styled } from "@mui/material/styles";
import Paper from "@mui/material/Paper";
import SchoolHeader from "../components/Schools/SchoolHeader";
import SchoolBody from "../components/Schools/SchoolBody";

const schoolData = [
  "Niagara College  Niagara on the Lake",
  "St. Thomas University    Fredericton",
  "Seneca College  King",
  "Durham College  Oshawa Campus",
  "Coquitlam College  Coquitlam Campus",
  "Trent University  Peterborough",
  "Lambton College  Sarnia Campus",
  "Lambton College  Mississauga Campus",
  "Alexander College  Burnaby Campus",
  "CodeCore College  Main Campus",
  "Alexander College  Vancouver Campus",
  "University of Regina  Main Campus",
  "Portage College  St. Paul",
  "Mohawk College   Mohawk College - Stoney Creek Campus",
  "Mohawk College   Mohawk College - Fennell",
  "College of New Caledonia  Vanderhoof Campus",
  "Trent University  Durham GTA",
  "North Island College  Port Alberni",
  "University of the Fraser Valley  Abbotsford",
  "Fanshawe College  London",
  "Selkirk College  Tenth Street",
  "Sheridan College  Hazel McCallion Campus",
  "Sheridan College  Trafalgar Road Campus",
  "Selkirk College  Silver King",
  "Selkirk College  Trail",
  "University of Canada West  Historic London Building",
  "Seneca College  Newnham",
  "College of New Caledonia  Quesnel Campus",
  "College of New Caledonia  Prince George",
  "North Island College  Campbell River campus",
  "Canadore College  College Drive",
  "NorQuest College  Edmonton",
  "Laurentian University   Sudbury Campus",
  "Cumberland College  Tisdale",
  "Medicine Hat College  Main Campus",
  "Okanagan College  Penticton Campus",
  "Vancouver Community College  VCC Downtown",
  "Acadia University  Main",
  "University of Waterloo  Waterloo",
  "Vancouver Island University  Nanaimo Campus",
  "Vancouver Island University  Cowichan Campus",
  "Selkirk College  Castlegar",
  "Fanshawe College  Woodstock",
  "Mount Allison University  Sackville ",
  "College of the North Atlantic  Labrador West",
  "Vancouver Island University  Powell River Campus",
  "Great Plains College  Biggar Campus",
  "Great Plains College  Kindersley Campus",
  "Great Plains College  Maple Creek Campus",
  "Great Plains College  Martensville Campus",
  "Great Plains College  Rosetown Campus",
  "Great Plains College  Swift Current Campus",
  "Great Plains College  Warman Campus",
  "Canadore College  Stanford Mississauga",
  "Memorial University of Newfoundland   Grenfell ",
  "Multihexa  College  Chicoutimi",
  "Cumberland College  Nipawin",
  "St.Lawrence College   Kingston Campus",
  "Memorial University of Newfoundland    St. John's ",
  "College of the Rockies  Fernie",
  "College of the Rockies  Gold Creek",
  "Medicine Hat College  Brooks Campus",
  "College of the Rockies  Golden",
  "Fanshawe College  St. Thomas",
  "MacEwan University  City Centre Campus",
  "College of the Rockies  Creston",
  "College of the Rockies  Invermere",
  "College of the Rockies  Kimberley",
  "University of New Brunswick  Saint John",
  "University of New Brunswick  Fredericton ",
  "College of the Rockies  Cranbrook",
  "Mount Saint Vincent University  Halifax Campus",
  "Trebas Institute  Montreal",
  "Trebas Institute  Toronto",
  "St.Lawrence College   Cornwall Campus",
  "Milestone College  Brossard,",
  "Canadian College  Vancouver",
  "Cambrian College  Sudbury",
  "St.Lawrence College   Alpha Campus",
  "St.Lawrence College   Brockville Campus",
  "Toronto School of Management  Main Campus",
  "Canadore College  Commerce Court",
  "Algonquin College  Pembroke Campus",
  "Cumberland College  Melfort",
  "University of Lethbridge  Lethbridge",
  "Fanshawe College  London South",
  "LaSalle College Vancouver  LaSalle College Vancouver",
  "University of Northern British Columbia  Prince George",
  "University of Saskatchewan  Saskatoon Campus",
  "Kwantlen Polytechnic University   Surrey Campus",
  "York University  York University - ",
  "Wilfrid Laurier University  Waterloo Campus",
  "Brock University  Niagara Region",
  "Wilfrid Laurier University  Brantford Campus",
  "Georgian College  South Georgian Bay",
  "Fanshawe College  Simcoe",
  "Adler University  Vancouver Campus",
  "Georgian College  Barrie",
  "University of Lethbridge  Calgary",
  "Georgian College  Orillia",
  "Durham College  Whitby Campus",
  "Fairleigh Dickinson University  Vancouver Campus",
  "VFS (Vancouver film school)  Vancouver Campus",
  "Durham College  Pickering Learning Site Campus",
  "Georgian College - ILAC TORONTO  TORONTO",
  "Justice Institute of British Columbia    New Westminster",
  "Saskatchewan Polytechnic  Saskatoon Campus",
  "Saskatchewan Polytechnic  Regina ",
  "College National  Main",
  "Niagara College  Toronto",
  "Loyalist College  Belleville Campus",
  "Loyalist College  Brunel",
  "Northern College - Pures  Northern College at Pures-Toronto",
  "Georgian College  Toronto",
  "Thompson River University  Williams Lake",
  "Humber College  Orangeville Campus",
  "Humber College  North Campus",
  "Humber College  Lakeshore Campus",
  "Humber College  IGS",
  "Conestoga  College   Stratford",
  "Conestoga  College   Waterloo",
  "Saskatchewan Polytechnic  Prince Albert ",
  "Seneca College  Seneca@York",
  "Okanagan College   Kelowna Campus",
  "Lakehead University  Thunder Bay Campus",
  "Conestoga  College   Cambridge - Downtown",
  "Lakehead University  Orillia Campus",
  "Conestoga  College   Cambridge - Fountain Street",
  "Sault College  Sault Ste. Marie Campus",
  "Saskatchewan Polytechnic  Moose Jaw ",
  "Wilfrid Laurier University  Kitchener Campus",
  "Conestoga  College   Kitchener - Downtown",
  "Vancouver Island University  Parksville Qualicum Campus",
  "North Island College  Comox Valley - Main Campus",
  "Okanagan College  Vernon Campus",
  "Sault College  Brampton Campus",
  "Sault College  Toronto Campus",
  "St Michel College  Montreal Campus",
  "Eton College  Vancouver Campus",
  "Thompson River University  Kamloops",
  "Conestoga  College   Brantford",
  "Coast Mountain College  Terrace",
  "Coast Mountain College  Prince Rupert",
  "Coast Mountain College  Smithers",
  "Coast Mountain College  Haida Gwaii",
  "Conestoga  College   Guelph",
  "Seneca College  Seneca International Academy",
  "Mohawk College   Institute for Applied Health Sciences at McMaster (IH)",
  "Conestoga  College   Kitchener - Doon",
  "Coast Mountain College  Hazelton",
  "Canadore College  West Parry Sound",
  "Niagara College  Welland",
  "Yukon University  Whitehorse",
  "Algonquin College  Perth Campus",
  "Kings University College  London",
  "Parkland College  Yorkton",
  "Red Deer College  Red Deer",
  "Cape Breton University  Main",
  "College of the North Atlantic  Corner Brook",
  "Lakeland College  Lloydminster",
  "Lakeland College  Vermilion",
  "College of the North Atlantic  Ridge Road",
  "Nipissing University  North Bay",
  "University of Manitoba  Winnipeg",
  "St. Francis Xavier University  Antigonish",
  "Columbia College  Vancouver",
  "Cambrian College  Hanson Toronto",
  "Cambrian College  Hanson Brampton",
  "Capilano University  Main",
  "St. Mary’s University  Calgary",
  "Sheridan College  Davis Campus",
  "Northern lights College   Dawson Creek",
  "Seneca College  Yorkgate",
  "Seneca College  Peterborough",
  "Manitoba Institute of Trades and Technology (MITT)  Henlow ",
  "Lambton College  Toronto Campus",
  "Canadore College  Stanford Brampton",
  "Canadore College  Aviation",
  "Canadore College  Stanford Scarborough",
  "Portage College  Lac La Biche",
  "Portage College  Cold Lake",
  "Algonquin College  Ottawa Campus",
  "Northern lights College   Fort St. John",
  "Vancouver Community College  VCC Broadway",
  "Vancouver Community College  VCC Annacis Island",
  "Seneca College  Markham",
  "North Island College  Port Hardy",
  "North Island College  Ucluelet",
  "College of the North Atlantic  Prince Philip Drive",
  "College of the North Atlantic  Gander",
  "College of the North Atlantic  Happy Valley-Goose Bay",
  "College of the North Atlantic  Bay St. George",
  "College of the North Atlantic  Carbonear",
  "College of the North Atlantic  Placentia",
  "College of the North Atlantic  Seal Cove",
  "College of the North Atlantic  Baie Verte",
  "College of the North Atlantic  St. Anthony",
  "College of the North Atlantic  Port aux Basques",
  "College of the North Atlantic  Clarenville",
  "College of the North Atlantic  Burin",
  "College of the North Atlantic  Grand Falls-Windsor",
  "Selkirk College  Victoria Street",
  "Selkirk College  Grand Forks",
  "College of the North Atlantic  Bonavista",
  "Cambrian College   North York",
  "Cambrian College  New Westminster",
  "Georgian College  Midland",
  "Georgian College  Orangeville",
  "Georgian College  Owen Sound",
  "Hawaii Pacific University  Downtown Campus",
  "Toronto Film School  Toronto",
  "Okanagan College  Salmon Arm",
  "International American University  Main",
  "International American University  Los Angeles",
  "Westcliff University  Irvine ",
  "Florida International University  Miami",
  "St.Lawrence College - ALPHA  Main",
  "University of Hartford  Main Campus",
  "Miami International University of Art &amp; Design  Miami - Main Campus",
  "Mohawk College   Mississauga  Campus",
  "Mohawk College   Centre for Aviation Technology at Hamilton International Airport (YHM)",
  "Portage College  Main Campus",
  "Concord University\t  Main Campus",
  "Gwynedd Mercy University  Bensalem",
  "James Madison University  Main Campus",
  "De Paul University  Main Campus",
  "Gwynedd Mercy University  Main Capmus",
  "Gwynedd Mercy University  Philadelphia ",
  "Nova Southeastern University  Main Campus",
  "Baylor University  Main Campus",
  "California State University, San Bernardino  San Bernardino",
  "Castleton University  Castleton Campus",
  "Florida Polytechnic University\t  Main Campus",
  "Hawaii Pacific University   makapu'u campus",
  "Hawaii Pacific University  HAWAII LOA CAMPUS",
  "Western Washington University  Main Campus",
  "Webster University  St. Louis Campus",
  "University of Nebraska at Kearney  Main Campus",
  "University of Missouri  Columbia",
  "University of Missouri  St. Louis",
  "University of Bridgeport    Main Campus",
  "Texas A&amp;M University-Corpus Christi  Main Campus",
  "Slippery Rock university  Main",
  "Pittsburg State University\t  Pittsburgh",
  "Manhattan College\t  Main Campus",
  "Lipscomb University  Main Campus",
  "Long Island University,   Brooklyn Campus",
  "Montserrat College of Art  Main Campus ",
  "Long Island University,   Post  Campus",
  "MSUB - Montana State University Billings   Billings",
  "University of Advancing Technology  Main Campus",
  "MacEwan University  Alberta Campus",
];

const LIMIT = 30;
const Item = styled(Paper)(({ theme }) => ({
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));
const data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18];

export default function Schools() {
  return (
    <>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
        }}
      >
        <h1>Schools</h1>
        <Grid item xs={12} sm={10} sx={{ width: "100vw", p: 1 }}>
          <SchoolHeader />
          <SchoolBody data={schoolData} limit={LIMIT} />
        </Grid>
      </Box>
    </>
  );
}
